### ISSUE TITLE
describe the benefits of playoutdelay in terms of metrics

### ISSUE THREAD

**Issue by fippo** [henbos/webrtc-extensions#8]
the [playout delay hint](https://henbos.github.io/webrtc-extensions/#dom-rtcrtpreceiver-playoutdelayhint) description lacks guidance on how to set the value and, more importantly, what metrics are useful to evaluate and tune the performance.

Adding such a description would greatly improve the value of the feature and make it accessible to the general web developer audience.

**Comment by henbos** [comment]
I think you would just set it to the desired playout delay.

A spec is not a user manual, it's a guide to the implementers. Looking at examples from other specs like [the ones in webrtc-pc](https://w3c.github.io/webrtc-pc/#example-10), I imagine a code example of this attribute would be rather useless since it would be a one-liner if we want to highlight how the API is used. "playoutDelayHint = x"

It sounds like you're saying that it is not clear what the API does? The value is _a hint to the User Agent about what playout delay is acceptable_, i.e. acceptable to the application's use case. This is a quote from the definition.

So if you want to ask for as little delay as possible, you hint a 0 and the UA will try to do its best without a glitchy experience. Otherwise if your use case thinks it's acceptable with a 10 s delay it can set it to 10. The UA might realize that network conditions are good enough to give you a smaller delay, but you've hinted that your application prefers a delay up to 10 s over stuttering.

As for which metrics to use to evaluate how good an implementation, I'm not sure that's in scope for a document like this.

What are you asking to be clarified exactly?

**Comment by jan-ivar** [comment]
I think it's fair to challenge the usability of a new API, as well as lack of guidance for usage *and* implementation. How large a value must implementers be prepared to support? 10 minutes?

Also, if someone changes the value, which they can do at any time btw, from 10 minutes to zero, what's supposed to happen? Are we supposed to skip 10 minutes of playback? Play back at double speed until we catch up? Lower only when encountering network difficulty?

**Comment by jan-ivar** [comment]
I think the usability question here is: what's a good input value for my use case? I worry numbers will be arrived at through tuning and tweaking based on one implementation. E.g. say it's`3`.

Now put yourself in the shoes of a different implementation which has a different default jitter buffer length. Are they supposed to add `3` seconds to *their* buffer length?

If the user expectation is a certain overall latency (which this API surface subtly implies), it hardly seems web compatible. IOW, numbers may be shooting too high/be the wrong granularity here for web compat.

I'd favor exposing APIs that don't rely on user agent behavior.

**Comment by jan-ivar** [comment]
> I'd favor exposing APIs that don't rely on user agent behavior.

One way to solve it might be to define the input as a *total target* jitter-buffer delay, rather than an addition to what the user agent defaults to. 

I.e. a target value ~matching measured [jitterbufferdelay](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-jitterbufferdelay)/[jitterBufferEmittedCount](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-jitterbufferemittedcount)

**Comment by fippo** [comment]
Look, this kind of feature is not new. [Flash's NetStream API](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/NetStream.html#bufferTime) had it for... at least 15 years.
For the streaming use-case its obvious. This feature is quite observable too (which suggests its testable). When setting the playoutdelay on the receivers in https://webrtc.github.io/samples/src/content/peerconnection/pc1/ to a high value like 5 seconds one can clearly see video delayed by that time and [jitterBufferDelay/jitterBufferEmittedCount_in_ms] in webrtc-internals goes to that value.

Yet what we see is this being launched for is not streaming, to quote from the merge request to M79:
```
Otherwise most likely Google Meet customers will experience sudden drop in quality for the period once origin trial expires in December.
```
From what I can see at a cursory glance gmeet sets a value of 0.12 which seems to increase quality? This seems like one of the good old x-goog features (which had the advantage that it was very clear that they were proprietary and there was no change request).

**Comment by henbos** [comment]
> One way to solve it might be to define the input as a total target jitter-buffer delay, rather than an addition to what the user agent defaults to.

It is my impression that the input is the absolute delay, not the additional delay on top of a user agent-specific default value. Please confirm this @kuddai so that we don't have wires crossed between intent of spec and actual implementation. If the input is treated as "additional delay" and not "absolute delay" then this API has interop problems.

With this in mind, I imagined that the application would use the same value no matter the user agent, and the user agent would try to achieve the target whenever reasonable, but protect the application against stuttering (unachievably low target based on network conditions) or unnecessarily long buffering (if network conditions are such that smooth playback can be assumed to be possible after X seconds, to not use a higher value than X even if it was asked for).

I thought we had implemented "= 0;" for the realtime/gaming use case to mean that "give me the smallest possible that doesn't stutter", but I heard the other day that we protect against stuttering by simply never going below the default? Does this mean that "= 0;" is essentially a NO-OP in Chrome, and we do not support the gaming use case with this API today?

As for protecting against unreasonably long buffering, I think the current implementation uses an implementation-specific upper limit that is fixed, not one based on network conditions. I.e. if you ask for additional delay within the supported range, you are going to get it, even if network conditions would allow smooth playback without additional buffering?

@kuddai to comment on implementation. There may be some confusion here.

**Comment by kuddai** [comment]
> > I'd favor exposing APIs that don't rely on user agent behavior.
> 
> One way to solve it might be to define the input as a total target jitter-buffer delay, rather than an addition to what the user agent defaults to.
> 
> I.e. a target value ~matching measured [jitterbufferdelay](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-jitterbufferdelay)/[jitterBufferEmittedCount](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-jitterbufferemittedcount)

Yes, there has been misunderstanding. This API already describes absolute delay on WebRTC networking layer, not additional one on top of the default browser behavior.

And its effect can be measured through differentiating [jitterbufferdelay](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-jitterbufferdelay) / [jitterBufferEmittedCount](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-jitterbufferemittedcount) . Alas taking diffs of 

_(jitterbufferdelay - prev_jitterbufferdelay)/(jitterBufferEmittedCount - prev_jitterBufferEmittedCount)_ 

with some fixed time interval. That is exactly how we monitored that change took effect in our experiments.

But there are  some special cases where the observed values in Chrome may different than the value set:

- If we are not receiving any audio or video, the readout would be close to 0 regardless of the hint.
- If the network condition is poor the internal congestion mechanism may choose a value higher than the hint.
- Audio and video buffers have physical memory limits. Different strategies can be utilized here depending on the browser. Currently the way it is done in Chrome, there is a maximum grow size for both audio and video buffers, 4 seconds for audio buffer and 10 seconds for video buffer. If playoutDelayHint is set above those values then Chrome tries to maintain maximum limit given memory constraint which correspond to 4 and 10 seconds respectively.


> I thought we had implemented "= 0;" for the realtime/gaming use case to mean that "give me the smallest possible that doesn't stutter", but I heard the other day that we protect against stuttering by simply never going below the default? Does this mean that "= 0;" is essentially a NO-OP in Chrome, and we do not support the gaming use case with this API today?

We do support the "realtime/gaming" use case; Chrome's default behavior is already to play out as soon as possible (given network constraints), so yes, "= 0;" is a NO-OP. In other browsers, one could imagine some amount of additional buffering to be happening by default, in which case "= 0;" would be valuable input to that browser.

> From what I can see at a cursory glance gmeet sets a value of 0.12 which seems to increase quality?

Correct. Through A/B testing we found for a meeting application 0.12 to be a good compromise between interactivity and quality.

(One could imagine 0.12 to be the new internal default value in webrtc, in which case "= 0;" would no longer be a NO-OP, but would map to the current default behavior of "play out as soon as possible".)

**Comment by henbos** [comment]
Thank you @kuddai. Does this clarify things, @jan-ivar and @fippo ?

**With regards to high values**
We could specify an upper limit to say that values larger than X are treated as X. For Chrome, 4 seconds would cover both audio and video, but what is a good X could be discussed. If we have a well-defined X, we could say that the browser must not play out sooner than the specified hint; this would make the API more well-defined and testable.

**With regards to low values**
I think the above comment highlights that it is useful to be able to say "play out as soon as possible". In this case, Chrome already tries to play out as soon as possible, but given the experiments it seems to be a good idea to allow the browser to change the default for the benefit of most use cases, and to make "play out as soon as possible" something that the application explicitly asks for. I had mistakenly thought that this was already the case, but I suppose that since they didn't have this API when they optimized the congestion control algorithms, they optimized it for the "play out as soon as possible" use case. If Firefox has done the same, it too would be a NO-OP to do "= 0", but I would think most uses of WebRTC does not require "play out as soon as possible".

**With regards to varying jitter buffer size**
@jan-ivar said

> Also, if someone changes the value, which they can do at any time btw, from 10 minutes to zero, what's supposed to happen? Are we supposed to skip 10 minutes of playback? Play back at double speed until we catch up? Lower only when encountering network difficulty?

Even without this API, the jitter buffer is allowed to change size, and this is already implementation-specific what value of [jitterBufferDelay](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-jitterbufferdelay) to get or what its delta is over time. There are some standardized metrics to measure the effects of acceleration and deceleration of audio in terms of samples: [insertedSamplesForDeceleration](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-insertedsamplesfordeceleration) and [removedSamplesForAcceleration](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-removedsamplesforacceleration).

If we can make acceleration and deceleration more well-defined that would be a good thing, with or without this API.

**Comment by jan-ivar** [comment]
Thanks, yes it helps clarify how Chrome works. Thanks also to @fippo for pointing out I can test it in Canary with https://webrtc.github.io/samples/src/content/peerconnection/pc1/ and web console:
```js
pc2.getReceivers()[0].playoutDelayHint = 2
```
I think we need to clarify in the spec better that the expected input value is a total ("delay" is perhaps an unfortunate word here that inherently sounds relative vs. e.g. "playoutBufferHint").

> Even without this API, the jitter buffer is allowed to change size, and this is already implementation-specific

Without this API, jitter is entirely in the user agent domain, even though it is observable through measurement and stats.

I think constraining user agents on how to handle jitter, and specifying how user agents must or mustn't react to changes made by JS using this new API, are potentially two different things.

For instance, if the goal of changing the value from `10` to `3` is not to drop 7 seconds of frames instantly, we should say so. Or if that is the goal, we should say that instead. Once we expose a web control surface, I think it helps web compat to specify how it works.

**Comment by fippo** [comment]
@kuddai thank you, that confirms I was looking in the right direction in general. If you ever want to explain this in great detail, webrtchacks.com is always open for interesting content ;-)

The overall problem here is that jitter buffers are *black magic* but I still do not see any reason the ability to tune the jitter buffer delay is different from any of the plethora of goog* peerconnection constraints we've had (and still have).

**Comment by henbos** [comment]
Thanks everyone. I think you've shown that there is a lot of room for improvement here. Let's file issues into actionable pieces. I'm happy that you have taken the time to participate.

> I think we need to clarify in the spec better that the expected input value is a total ("delay" is perhaps an unfortunate word here that inherently sounds relative vs. e.g. "playoutBufferHint").

Filed #9.

> I think constraining user agents on how to handle jitter, and specifying how user agents must or mustn't react to changes made by JS using this new API, are potentially two different things.
> 
> For instance, if the goal of changing the value from 10 to 3 is not to drop 7 seconds of frames instantly, we should say so. Or if that is the goal, we should say that instead. Once we expose a web control surface, I think it helps web compat to specify how it works.

Filed #10.

> How large a value must implementers be prepared to support? 10 minutes?

Filed #11.

> And its effect can be measured through differentiating jitterbufferdelay / jitterBufferEmittedCount.

Filed #12.

Is there anything else that I've missed or glossed over?

**Comment by kuddai** [comment]
Thanks everyone for your feedback. It really puts perspective on what we are lacking in our explanation. Then I will tackle these issues mentioned above one by one. Please join us in the discussions there as well. 

Especially in the issue #10 as we didn't bring it in the spec and overall hid under phrase "it is up to the User Agent to overwrite it" which includes memory constraints. The main problem here is that jitter buffers are kinda "black boxes", and one can easily imagine implementation where buffer grows until the system memory exhausted. That is why mentioning explicitly current Chrome memory/seconds limits purely fits the spec description as this is implementation detail.

**Comment by henbos** [comment]
Given the different issues filed and PRs merged, I think we can close this granddaddy issue and refer to the follow-up issues. Cheers!
